[project]
name = "interface-ai-take-home"
version = "0.1.0"
description = ""
authors = [
    {name = "Youssef Qteishat",email = "youssef.qt1@gmail.com"}
]
readme = "README.md"
requires-python = "^3.12"
dependencies = [
    "fastapi (>=0.115.0)",
    "jinja2 (>=3.1.0)",
    "python-multipart (>=0.0.9)",
    "uvicorn (>=0.30.0)",
    "anthropic (>=1.7.0,<2.0.0)",
    "httpx (>=0.28.1,<0.29.0)",
    "pydantic (>=2)",
    "pyyaml (>=6.0.3,<7.0.0)",
    "typer (>=0.27.2,<0.28.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
